version: '3.1'
services:
  bot:
    container_name: newcoins_bot
    build: .
    restart: always
    env_file:
      - .env
    command: ["python", "coin_checker.py"]
    depends_on:
      - db
  db:
    container_name: newcoins_db
    image: postgres:10.1
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: